language: erlang

env:
   - ST=GemStone-2.4.5.2
   - ST=GemStone-3.1.0.4

#   - ST=GemStone-2.4.4.1
#   - ST=GemStone-2.4.4.8
#   - ST=GemStone-2.4.5
#   - ST=GemStone-3.0.1

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh  -verbose
